---
title: "Assignment 4"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(fig.align = 'center')
```

```{r packages, message=F}
require(curry)
require(GA)
require(ggplot2)
require(reshape2)
library(ConsPlan)
```


```{r Time function}
time <- function(perm,distMatrix){
  n_jobs     <- ncol(distMatrix)
  n_machines <- nrow(distMatrix)
  dist       <- matrix(NA, nrow=n_machines, ncol=n_jobs)
  dist[1,]   <- cumsum(distMatrix[1,perm])
  dist[,1]   <- cumsum(distMatrix[,perm[1]])
  for (i in 2:n_machines){
    for (j in 2:n_jobs){
      dist[i,j] <- distMatrix[i,perm[j]] + 
        max(dist[i,j-1],dist[i-1,j])
    }
  }
  makespan   <- dist[n_machines,n_jobs]
  return(makespan)
}

fitness <- function(perm,distMatrix){
  return(1/time(perm,distMatrix))
}

# Qua si legge time_matrix
time_matrix <- as.matrix(read.csv("j20-m5",sep=" ",header = F))
n_jobs <- ncol(time_matrix)


GA.fit <- ga(type = "permutation",
  fitness = fitness,
  distMatrix = time_matrix,
  lower = 1,
  upper = n_jobs,
  popSize = 1000, #ci mette molto tempo ma arriva alla soluzione ottimale
  maxiter = 10000,
  run = 300,
  pmutation = 0.2,
  keepBest = TRUE,
  monitor = NULL)

summary(GA.fit)

time(GA.fit@solution[1,],distMatrix=time_matrix)

out <- plot(GA.fit, main = "GA progression")

melt(out[,c(1:3,5)],id.var="iter") %>% 
  mutate(time=1/value) -> df1

ggplot(df1, aes(x = iter, y = time, 
               group = variable, colour = variable)) +
  xlab("Generation") + ylab("Time values") +
  #geom_point(aes(shape = variable)) +
  geom_line(aes(lty = variable)) +
  scale_colour_brewer(palette = "Set1") +
  theme_bw() +
  labs(title = "GA Progression")
```

```{r 50-10}
time_matrix <- as.matrix(read.csv("j50-m10",sep=" ",header=F))
n_jobs <- ncol(time_matrix)


GA.fit <- ga(type = "permutation",
  fitness = fitness,
  distMatrix = time_matrix,
  lower = 1,
  upper = n_jobs,
  popSize = 500,
  maxiter = 10000,
  run = 200,
  pmutation = 0.2,
  keepBest = TRUE,
  monitor = NULL)

summary(GA.fit)

time(GA.fit@solution[1,],distMatrix=time_matrix)

out <- plot(GA.fit, main = "GA progression")

melt(out[,c(1:3,5)],id.var="iter") %>% 
  mutate(time=1/value) -> df1

ggplot(df1, aes(x = iter, y = time, 
               group = variable, colour = variable)) +
  xlab("Generation") + ylab("Time values") +
  #geom_point(aes(shape = variable)) +
  geom_line(aes(lty = variable)) +
  scale_colour_brewer(palette = "Set1") +
  theme_bw() +
  labs(title = "GA Progression")
```

```{r}
funObj <- tail_curry(time,time_matrix)

swapJobs <- function(perm){
    n <- length(perm)
    pair <- sample.int(n,2) # si sceglie una copia
    nmin <- min(pair)         
    nmax <- max(pair)
    newperm <- perm
    newperm[nmin] <- perm[nmax]
    newperm[nmax] <- perm[nmin]
    return(as.numeric(newperm))
}

start <- as.numeric(sample(1:n_jobs,n_jobs))
start

sa_opt =  sann(start.seq = start, fn = funObj,
               gr = swapJobs, maxit = 100000, 
               REPORT = 1000, tmax = 100, temp = 9000)

```

